[package]
name = "image2ascii"
version = "0.1.0"
authors = ["whamer100 <whammer100@aol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
image = "0.22.0"